{
  "name": "template – Power BI Desktop",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "cs-CZ",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "cs-CZ",
    "tables": [
      {
        "name": "CRS",
        "lineageTag": "2f54c87b-f396-49a5-bf67-6c7e19d8dbdd",
        "columns": [
          {
            "name": "Id",
            "dataType": "string",
            "sourceColumn": "Id",
            "lineageTag": "121ad953-9994-42be-9998-8cb8439d1a2d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "24eea8a5-8a56-478d-9157-4517b20b211a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Priority",
            "dataType": "string",
            "sourceColumn": "Priority",
            "lineageTag": "4816d686-4fb8-4664-a23c-545d86725716",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Release",
            "dataType": "string",
            "sourceColumn": "Release",
            "lineageTag": "cab37789-02ec-4448-bacd-8d103deb992e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "b349c2de-d476-4c79-99da-9ce8d70d49ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CRS-05e0f04c-6c18-4520-8b7d-31aee93f8134",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(DataSource), null, true),",
                "    CRS_Sheet = Zdroj{[Item=\"CRS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(CRS_Sheet, [PromoteAllScalars=true]),",
                "    #\"Odebrané prázdné řádky\" = Table.SelectRows(#\"Záhlaví se zvýšenou úrovní\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Odebrané prázdné řádky\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Overdues requirements",
            "expression": [
              "CALCULATE (",
              "    SUMX (",
              "        CRS,",
              "        IF (",
              "            DATEVALUE([Release]) < TODAY (),",
              "            1,",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1e472b27-8719-4f55-a072-92539ff36317"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_6a3f7aff-e1c3-4db8-b433-cc63bf6a62b1",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5c1c82e7-34ab-42ef-a646-d5b670bc5f87",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "0afdb96d-ca33-4198-bd79-3d74b0c44ae8",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Rok",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9b265b2c-0afd-40fb-a7e4-811d647d6e6d",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "8f94e76d-f7b1-4b7c-a4ae-8045694b853c",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Měsíc",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "5bf31e7e-6c6e-412a-acd2-95803df1d8e4",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "fd87926d-3e86-424d-ab76-9fa37bf829f4",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Čtvrtletí",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "cb69ce18-7edf-4ff8-b167-07a3ddbe31be",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Den",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "e79e0def-b507-4fe5-8b4d-0447309b0199",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_6a3f7aff-e1c3-4db8-b433-cc63bf6a62b1-2ca23793-fb59-41b8-9ab0-157c18cb59fe",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchie dat",
            "lineageTag": "c288656d-3d80-49a1-8231-dd25fe7e359e",
            "levels": [
              {
                "name": "Rok",
                "ordinal": 0,
                "column": "Rok",
                "lineageTag": "8d7f8b48-a866-49f7-91a6-20e925c2c045"
              },
              {
                "name": "Čtvrtletí",
                "ordinal": 1,
                "column": "Čtvrtletí",
                "lineageTag": "ab31753f-e111-451e-bc87-1dc7f03ad196"
              },
              {
                "name": "Měsíc",
                "ordinal": 2,
                "column": "Měsíc",
                "lineageTag": "b4bd1621-d8a4-4e7d-ace8-6c051e467805"
              },
              {
                "name": "Den",
                "ordinal": 3,
                "column": "Den",
                "lineageTag": "cf8b2491-85a7-4894-b304-ee961d7b7bbb"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "SYRS",
        "lineageTag": "fc0f24b5-8e7c-4684-96b1-3eb6514e8b97",
        "columns": [
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "8afad6b1-8513-4e49-bcf3-ec455daf1871",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReqType",
            "dataType": "string",
            "sourceColumn": "ReqType",
            "lineageTag": "0db05205-06c2-48fa-a75b-de0d7cc56df8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Domain",
            "dataType": "string",
            "sourceColumn": "Domain",
            "lineageTag": "eb0081cb-17bb-4105-99e3-d7d6dfd8da48",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CRS_ID",
            "dataType": "string",
            "sourceColumn": "CRS_ID",
            "lineageTag": "6b211072-89b7-404d-bc14-2520393c0ffb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID",
            "lineageTag": "26d33ceb-ad1e-4524-ba8a-3bea9d00f13c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SYRS-d8350e5f-c67b-4155-8f71-c23d549bb3ba",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(DataSource), null, true),",
                "    SYRS_Sheet = Zdroj{[Item=\"SYRS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(SYRS_Sheet, [PromoteAllScalars=true]),",
                "    #\"Odebrané prázdné řádky\" = Table.SelectRows(#\"Záhlaví se zvýšenou úrovní\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Odebrané prázdné řádky\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "CRS_Measurements",
        "lineageTag": "5d8f370e-f03e-4035-9306-2f222b355ba2",
        "columns": [
          {
            "name": "CRS_ID",
            "dataType": "string",
            "sourceColumn": "CRS_ID",
            "lineageTag": "fb5f31e0-aa00-4523-bc20-904bcb856858",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "bb9cb23f-b667-4b76-b5dc-4bf9167ec432",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SatisfiedByCustomer",
            "dataType": "string",
            "sourceColumn": "SatisfiedByCustomer",
            "lineageTag": "1e89d1de-bfe8-4ab1-b446-86f4e3a16450",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateUpdate",
            "dataType": "string",
            "sourceColumn": "DateUpdate",
            "lineageTag": "e02a555f-2bdb-49f1-9329-feb8a999decb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CRS_Measurements-17b05c6b-6be8-4438-b223-09442a445caa",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(DataSource), null, true),",
                "    CRS_Measurements_Sheet = Zdroj{[Item=\"CRS_Measurements\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(CRS_Measurements_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Záhlaví se zvýšenou úrovní\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "SYRS_Measurements",
        "lineageTag": "8ebd929f-518d-4438-8b3d-12e6d9647801",
        "columns": [
          {
            "name": "SYRS_ID",
            "dataType": "string",
            "sourceColumn": "SYRS_ID",
            "lineageTag": "51af37a4-568d-47ab-a915-c8a8eb11ea8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "2ef6c243-79f7-45fd-9347-9dc6a26633cc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateUpdate",
            "dataType": "string",
            "sourceColumn": "DateUpdate",
            "lineageTag": "acbf3093-ecb4-49e5-947e-c2cab209a84e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SYRS_Measurements-df7df104-eb13-488b-acd7-c2458c81d1c7",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(DataSource), null, true),",
                "    SYRS_Measurements_Sheet = Zdroj{[Item=\"SYRS_Measurements\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(SYRS_Measurements_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Záhlaví se zvýšenou úrovní\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "CRS_Latest_Measurements",
        "lineageTag": "168dc848-d8cd-40ad-9704-9378792cd569",
        "columns": [
          {
            "name": "CRS_ID",
            "dataType": "string",
            "sourceColumn": "CRS_ID",
            "lineageTag": "624511ab-1a0b-490d-85d4-501af3750eb3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "DateUpdate",
            "dataType": "string",
            "sourceColumn": "DateUpdate",
            "lineageTag": "6fd5c76f-7bfc-4130-ac3a-e42678d9e155",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "c5622483-d67f-4908-bf7d-4d6d743c8b92",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SatisfiedByCustomer",
            "dataType": "string",
            "sourceColumn": "SatisfiedByCustomer",
            "lineageTag": "5cfe5538-304d-4940-8f91-80166dd62005",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CRS_Latest_Measurements-03b345d9-ddd0-4783-bc9c-b53c14991bb3",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = CRS_Measurements,",
                "    #\"Filtrované řádky\" = Table.SelectRows(Zdroj, each ([DateUpdate] = \"3/5/21\"))",
                "in",
                "    #\"Filtrované řádky\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigace"
          }
        ]
      },
      {
        "name": "SYRS_Latest_Measurements",
        "lineageTag": "d15eeec7-85e9-44fa-a7b1-7e632d53be45",
        "columns": [
          {
            "name": "SYRS_ID",
            "dataType": "string",
            "sourceColumn": "SYRS_ID",
            "lineageTag": "6f6753a6-e646-4c59-9cba-82d5cee82953",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateUpdate",
            "dataType": "string",
            "sourceColumn": "DateUpdate",
            "lineageTag": "dfe2b4c1-8a7e-41b1-a860-022f8b52cd67",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "8eabe76f-b75b-48c4-8762-2e86d214f3ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SYRS_Latest_Measurements-229fd225-c57d-449e-9d70-c1561a2f4b53",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = SYRS_Measurements,",
                "    #\"Filtrované řádky\" = Table.SelectRows(Zdroj, each ([DateUpdate] = \"3/10/21\"))",
                "in",
                "    #\"Filtrované řádky\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigace"
          }
        ]
      },
      {
        "name": "Stories",
        "lineageTag": "29aae8ca-675b-4b3f-ac79-932d4fdaae8f",
        "columns": [
          {
            "name": "Column",
            "dataType": "string",
            "sourceColumn": "Column",
            "lineageTag": "39db2333-49d8-434c-8a53-c8f2b6beffc1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sum",
            "dataType": "int64",
            "sourceColumn": "Sum",
            "formatString": "0",
            "lineageTag": "17144e07-b425-45ac-a550-567373d5856b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Stories-20310032-e80c-44af-b99a-b964a1255d33",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(\"C:\\Users\\marty\\OneDrive\\Škola\\10. semestr\\Diplomová práce\\Projekt\\Template\\template2.xlsx\"), null, true),",
                "    Stories_Sheet = Zdroj{[Item=\"Stories\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(Stories_Sheet, [PromoteAllScalars=true]),",
                "    #\"Změněný typ\" = Table.TransformColumnTypes(#\"Záhlaví se zvýšenou úrovní\",{{\"Column\", type text}, {\"Sum\", Int64.Type}})",
                "in",
                "    #\"Změněný typ\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Parameters",
        "lineageTag": "0ecdfc98-ce4e-4095-816c-24ac3e4f1939",
        "columns": [
          {
            "name": "Key",
            "dataType": "string",
            "sourceColumn": "Key",
            "lineageTag": "8916bba6-9751-4611-8fc7-dc70ecbc4772",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "lineageTag": "6abdcb76-30e7-49f6-8251-ed877e903672",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Parameters-56f6e454-6d30-4774-8f93-26a3c4a9f53a",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(\"C:\\Users\\marty\\OneDrive\\Škola\\10. semestr\\Diplomová práce\\Projekt\\Template\\template2.xlsx\"), null, true),",
                "    Parameters_Sheet = Zdroj{[Item=\"Parameters\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(Parameters_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Záhlaví se zvýšenou úrovní\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Project start",
            "expression": [
              "FORMAT(CALCULATE (",
              "    VALUES ( Parameters[Value] ),",
              "    FILTER ( ALL ( Parameters[Key] ),  Parameters[Key] = \"ProjectStart\" )",
              "), \"DD/MM/YYYY\")"
            ],
            "lineageTag": "a377b0a5-d07a-42b1-9114-6b4be081cd91"
          },
          {
            "name": "Actual",
            "expression": [
              "",
              "VAR tab = AddColumns(SUMMARIZECOLUMNS(Team[Id], Team[CostPerHour], \"Sum\", SUM(Attendance[WorkedHours])), \"Salary\", [CostPerHour]*[Sum])",
              "return sumx(tab, [Salary])"
            ],
            "formatString": "0",
            "lineageTag": "00b9651c-e21c-4e06-8968-d980d9d7354d"
          },
          {
            "name": "Budget",
            "expression": [
              "int(CALCULATE (",
              "    VALUES ( Parameters[Value] ),",
              "    FILTER ( ALL ( Parameters[Key] ),  Parameters[Key] = \"Budget\" ))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4aba883d-dc74-467f-8656-71783ce3fb8e"
          },
          {
            "name": "Planned - StoriesPoints",
            "expression": [
              "",
              "var avgHoursPerWorker = CALCULATE(SUM(Stories[Sum])/COUNT(Team[Id]))",
              "VAR tab = ADDColumns(Team, \"PlannedCost\", [CostPerHour]*avgHoursPerWorker)",
              "return SUMX(tab, [PlannedCost])"
            ],
            "lineageTag": "4deff5a3-b96d-4374-bacc-130208a51553",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Current date",
            "expression": "FORMAT(TODAY(), \"DD/MM/YYYY\")",
            "lineageTag": "b08ab68e-58f1-452d-89eb-25db4684d7f6"
          },
          {
            "name": "Days to release",
            "expression": "DATEDIFF(NOW(), [Project release], DAY)",
            "formatString": "0",
            "lineageTag": "67cfef8d-26c3-4084-8796-4693ef505a0b"
          },
          {
            "name": "Project release",
            "expression": [
              "CALCULATE (",
              "    VALUES ( Parameters[Value] ),",
              "    FILTER ( ALL ( Parameters[Key] ),  Parameters[Key] = \"ProjectRelease\" )",
              ")"
            ],
            "lineageTag": "108663a8-3bb6-436b-9d89-64087de4913e"
          },
          {
            "name": "Past days",
            "expression": "DATEDIFF([Project start], NOW(), DAY)",
            "formatString": "0",
            "lineageTag": "cc710bd7-539f-4f3c-af7e-b4014fc30ebd"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Team",
        "lineageTag": "8e233037-5bbb-4be1-8ccb-c660a45f7bc5",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "c32c7f8e-cd22-4dd7-96e0-fee30417ad0c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "cda16e2e-e4f3-45ec-94f7-6fa8f62723ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CostPerHour",
            "dataType": "int64",
            "sourceColumn": "CostPerHour",
            "formatString": "0",
            "lineageTag": "feede95e-6c63-4694-a734-523a954be4d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Role",
            "dataType": "string",
            "sourceColumn": "Role",
            "lineageTag": "562b51ed-07fb-4b21-be25-836bbd23e77b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Team-63188cad-270b-4259-b3ac-5476eed3d538",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(\"C:\\Users\\marty\\OneDrive\\Škola\\10. semestr\\Diplomová práce\\Projekt\\Template\\template2.xlsx\"), null, true),",
                "    Team_Sheet = Zdroj{[Item=\"Team\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(Team_Sheet, [PromoteAllScalars=true]),",
                "    #\"Změněný typ\" = Table.TransformColumnTypes(#\"Záhlaví se zvýšenou úrovní\",{{\"Id\", Int64.Type}, {\"Name\", type text}, {\"CostPerHour\", Int64.Type}, {\"Role\", type text}})",
                "in",
                "    #\"Změněný typ\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Attendance",
        "lineageTag": "bb7cedbb-20cc-4f01-af5b-be94b9dc7509",
        "columns": [
          {
            "name": "MemberId",
            "dataType": "int64",
            "sourceColumn": "MemberId",
            "formatString": "0",
            "lineageTag": "95930be7-38d1-4e19-8e38-e1585b024aac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Day",
            "dataType": "dateTime",
            "sourceColumn": "Day",
            "formatString": "Long Date",
            "lineageTag": "8ca3a976-0bfe-4198-9a77-dc8f180d2a9a",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variace",
                "relationship": "e7612fab-4c2b-4255-b961-6fb33a4841b6",
                "defaultHierarchy": {
                  "table": "LocalDateTable_6158647b-1397-4174-b3cf-bcbde82498c6",
                  "hierarchy": "Hierarchie dat"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "WorkedHours",
            "dataType": "int64",
            "sourceColumn": "WorkedHours",
            "formatString": "0",
            "lineageTag": "0884bbe1-33c5-42dc-89cc-6aca1dd44bf0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Activity",
            "dataType": "string",
            "sourceColumn": "Activity",
            "lineageTag": "3875cf98-9fd0-4cb6-9071-8e0b30495702",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Attendance-b5922c79-a780-46e7-97de-e82d47f17c65",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Zdroj = Excel.Workbook(File.Contents(\"C:\\Users\\marty\\OneDrive\\Škola\\10. semestr\\Diplomová práce\\Projekt\\Template\\template2.xlsx\"), null, true),",
                "    Attendance_Sheet = Zdroj{[Item=\"Attendance\",Kind=\"Sheet\"]}[Data],",
                "    #\"Záhlaví se zvýšenou úrovní\" = Table.PromoteHeaders(Attendance_Sheet, [PromoteAllScalars=true]),",
                "    #\"Změněný typ\" = Table.TransformColumnTypes(#\"Záhlaví se zvýšenou úrovní\",{{\"MemberId\", Int64.Type}, {\"Day\", type date}, {\"WorkedHours\", Int64.Type}})",
                "in",
                "    #\"Změněný typ\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_6158647b-1397-4174-b3cf-bcbde82498c6",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "4359eed1-c530-48c1-a1e0-934768c3e28e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "8d2d06cb-c3e1-4afa-bb20-6669aae3ec20",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Rok",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "d17b776f-cd53-4e39-9267-b8b27bc71fa8",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "273e5080-c5e3-4a4e-ba40-d5f2a9461258",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Měsíc",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "d42e7538-eac7-4175-99ed-6bcdcc730403",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "84e31209-9b75-42fb-8e7a-afe12207b086",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Čtvrtletí",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "54894cdd-36f9-4773-92bb-0a797fd8be92",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Den",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "dc31caa0-2f96-4e56-80ed-8e1f0a8243da",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_6158647b-1397-4174-b3cf-bcbde82498c6-1c949724-8bea-4119-8534-6970da73fcb5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Attendance'[Day])), 1, 1), Date(Year(MAX('Attendance'[Day])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchie dat",
            "lineageTag": "080f0c6b-2af2-43f1-8fe9-aaf715e86dd8",
            "levels": [
              {
                "name": "Rok",
                "ordinal": 0,
                "column": "Rok",
                "lineageTag": "af84e646-eec2-40a8-bb2a-ef4a3903f042"
              },
              {
                "name": "Čtvrtletí",
                "ordinal": 1,
                "column": "Čtvrtletí",
                "lineageTag": "bdb249e1-6117-4697-9ecb-ed27c0c9e633"
              },
              {
                "name": "Měsíc",
                "ordinal": 2,
                "column": "Měsíc",
                "lineageTag": "8980add9-b9ec-42c9-9d45-1c4d351c59f2"
              },
              {
                "name": "Den",
                "ordinal": 3,
                "column": "Den",
                "lineageTag": "702c1733-c18d-49aa-8753-0ab07e3d7116"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Tabulka",
        "lineageTag": "011243e3-bceb-4908-84c6-1516f798e61d",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Category",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS[Category]",
            "lineageTag": "bfe9e180-fb7a-43ad-b537-732e7fc03b9a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Počet",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Počet]",
            "formatString": "0",
            "lineageTag": "060798bc-8120-47fb-bad6-870298248c58",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SatisfiedByCustomer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS_Latest_Measurements[SatisfiedByCustomer]",
            "lineageTag": "b922af05-97e1-4967-b168-0cf777b415d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Tabulka-d83ae70c-9c2a-4e6d-bde0-75a7db7326c7",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "SUMMARIZECOLUMNS(CRS[Category],CRS_Latest_Measurements[SatisfiedByCustomer], \"Počet\", COUNT(CRS_Latest_Measurements[SatisfiedByCustomer]))"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fd92201a00324f5e8d181f1e6c6f8b83"
          }
        ]
      },
      {
        "name": "Tabulka 2",
        "lineageTag": "0df78e32-36ad-4db5-ba49-108d02b514d7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CRS_ID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS_Measurements[CRS_ID]",
            "lineageTag": "91492bfd-ed35-4a63-9cd7-4e05cadbc4fe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Status",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS_Measurements[Status]",
            "lineageTag": "3d870677-90d2-4b5f-83c3-51930fee083b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SatisfiedByCustomer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS_Measurements[SatisfiedByCustomer]",
            "lineageTag": "46c40062-8a4b-43fe-924c-511e34deefd7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateUpdate",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CRS_Measurements[DateUpdate]",
            "lineageTag": "25deee7e-a07b-456b-ae55-40e49301fd9f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Tabulka 2-33609030-46d7-419d-8a8a-df87fb88b811",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CRS_Measurements"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "65d49ce9043a487e8654d683362ee15b"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "56051bb6-cadf-4fe6-aae4-76b232f597fd",
        "fromTable": "CRS_Measurements",
        "fromColumn": "CRS_ID",
        "toTable": "CRS",
        "toColumn": "Id"
      },
      {
        "name": "34dff6bc-9416-498e-9b6f-f56d610e463d",
        "fromTable": "SYRS",
        "fromColumn": "CRS_ID",
        "toTable": "CRS",
        "toColumn": "Id"
      },
      {
        "name": "51250107-5aab-4a1a-b69c-dc5d625b7acd",
        "fromTable": "CRS_Latest_Measurements",
        "fromColumn": "CRS_ID",
        "toTable": "CRS",
        "toColumn": "Id"
      },
      {
        "name": "8154ee14-4b3f-4dd0-956e-daa359c170db",
        "fromTable": "SYRS_Measurements",
        "fromColumn": "SYRS_ID",
        "toTable": "SYRS",
        "toColumn": "ID"
      },
      {
        "name": "9d36bd07-5c4f-4f09-b648-1d41fdacd8be",
        "fromTable": "SYRS_Latest_Measurements",
        "fromColumn": "SYRS_ID",
        "toTable": "SYRS",
        "toColumn": "ID"
      },
      {
        "name": "e7612fab-4c2b-4255-b961-6fb33a4841b6",
        "fromTable": "Attendance",
        "fromColumn": "Day",
        "toTable": "LocalDateTable_6158647b-1397-4174-b3cf-bcbde82498c6",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "51796de7-31a0-4242-a81f-484b4526d56a",
        "fromTable": "Attendance",
        "fromColumn": "MemberId",
        "toTable": "Team",
        "toColumn": "Id"
      }
    ],
    "cultures": [
      {
        "name": "cs-CZ",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "expressions": [
      {
        "name": "DataSource",
        "kind": "m",
        "expression": "\"C:\\Users\\marty\\OneDrive\\Škola\\10. semestr\\Diplomová práce\\Projekt\\Template\\template2.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "131ad573-6af3-4988-a475-e7c69c4006b4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigace"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.103.881.0 (22.03)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"CRS\",\"SYRS\",\"CRS_Measurements\",\"SYRS_Measurements\",\"DataSource\",\"CRS_Latest_Measurements\",\"SYRS_Latest_Measurements\",\"Stories\",\"Parameters\",\"Team\",\"Attendance\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":true,\"LocalPerspectives\":true,\"LocalRelationships\":true,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}